version: '3'

services:
  web:
    image: openconceptlab/oclmap:${TAG-dev}
    build:
      context: .
      target: build
      args:
        NODE_ENV: development
    ports:
      - "4004:4004"
      - "4005:35729"
      - "6008:6006"
    restart: on-failure
    volumes:
      - .:/app:z
