version: '3'

services:
  web:
    image: openconceptlab/oclmap:${TAG-latest}
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "4004:4004"
    restart: on-failure
    environment:
      - API_URL=${API_URL-http://127.0.0.1:8000}
      - NODE_ENV=${NODE_ENV-development}
      - WEB_PORT=4004
      - GA_ACCOUNT_ID=${GA_ACCOUNT_ID-UA-000000-01}
      - ERRBIT_URL
      - ERRBIT_KEY
      - HOTJAR_ID
